version: 2
updates:
  - package-ecosystem: maven
    directory: /quarkus-workshop-super-heroes
    open-pull-requests-limit: 40
    schedule:
      interval: daily
    labels:
      - "version-upgrade"
    pull-request-branch-name:
      separator: "_"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - infra
    pull-request-branch-name:
      separator: "_"
