name: Build

on:
  push:
    branches:
      - main

jobs:  
  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install --file quarkus-workshop-super-heroes/pom.xml -Pnative -Dquarkus.native.container-build=true -DskipITs

  publication:
    needs: [build_java11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Site generation
        run: |  
          sudo apt-get install graphviz

          cd quarkus-workshop-super-heroes/docs      
          mvn install
          
          # make an index.html
          cp target/generated-asciidoc/spine.html target/generated-asciidoc/index.html
          cp target/generated-asciidoc/spine-azure.html target/generated-asciidoc/index-azure.html

          # Move things around to preserve the super-heroes structure
          mkdir -p target/site/super-heroes
          cp -R target/generated-asciidoc/* target/site/super-heroes
          # Move the redirect.html page to the root
          cp target/generated-asciidoc/redirect.html target/site/index.html

      - name: Publication
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./quarkus-workshop-super-heroes/docs/target/site