name: Pull Request

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'quarkus-workshop-super-heroes/**'
      - '.github/**'

jobs:
  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install --file quarkus-workshop-super-heroes/pom.xml -Pnative -Dquarkus.native.container-build=true -DskipITs

