name: Generate zips

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'quarkus-workshop-super-heroes/docs/**'
      - 'quarkus-workshop-super-heroes/dist/**'
jobs:
  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install --file quarkus-workshop-super-heroes/pom.xml
  publication:
    needs: [ build_java11 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Generate zips
        run: |
          cd quarkus-workshop-super-heroes/
          mvn assembly:single -N
      - name: Commit zips
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'ci-action@users.noreply.github.com'
          git commit -am "Automated zip generation"
          git push
