name: Generate zips

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'quarkus-workshop-super-heroes/docs/**'
      - 'quarkus-workshop-super-heroes/dist/**'
jobs:
  build_java17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Skeleton build with Maven
        run: mvn -B install --file quarkus-workshop-super-heroes/pom.xml -Pnative -Dquarkus.native.container-build=true -DskipITs
      - name: Microservices build with Maven
        run: mvn -B install --file quarkus-workshop-super-heroes/pom.xml -Pcomplete
      - name: Extension build with Maven
        run: mvn -B install -f quarkus-workshop-super-heroes/super-heroes/extension-version/pom.xml
  publication:
    needs: [ build_java17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Generate zips
        run: |
          cd quarkus-workshop-super-heroes/
          mvn assembly:single -N
      - name: Commit zips
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'ci-action@users.noreply.github.com'
          git commit -am "Automated zip generation"
          git push
